spring.config.import=optional:application-secrets.properties

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.port=${SERVER_PORT}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
